In [1]:
# loading packages

import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# loading the dataset

dataset = pd.read_excel("Folds5x2_pp.xlsx")

X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values

In [3]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [4]:
# splitting the data into training set and testing set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [5]:
# initialzing the artificial neural network

ann = tf.keras.models.Sequential()

In [6]:
# adding the input layer and the first hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [7]:
# adding the second hiddden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [8]:
# adding the output layer

ann.add(tf.keras.layers.Dense(units=1))

In [9]:
# compiling the artificial neural network

ann.compile(optimizer='adam', loss='mean_squared_error')

In [10]:
# training the artificial neural network model on the training set

ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 793us/step - loss: 146007.8906
Epoch 2/100
240/240 [==============================] - 0s 741us/step - loss: 749.5964
Epoch 3/100
240/240 [==============================] - 0s 787us/step - loss: 557.3624
Epoch 4/100
240/240 [==============================] - 0s 858us/step - loss: 521.8374
Epoch 5/100
240/240 [==============================] - 0s 854us/step - loss: 482.1977
Epoch 6/100
240/240 [==============================] - 0s 971us/step - loss: 438.6703
Epoch 7/100
240/240 [==============================] - 0s 996us/step - loss: 393.5296
Epoch 8/100
240/240 [==============================] - 0s 833us/step - loss: 347.2216
Epoch 9/100
240/240 [==============================] - 0s 840us/step - loss: 301.4778
Epoch 10/100
240/240 [==============================] - 0s 862us/step - loss: 254.6367
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 178.6480
Epoch 12/100
240/240 [=============================

240/240 [==============================] - 0s 557us/step - loss: 27.3281
Epoch 96/100
240/240 [==============================] - 0s 544us/step - loss: 26.8392
Epoch 97/100
240/240 [==============================] - 0s 536us/step - loss: 26.4515
Epoch 98/100
240/240 [==============================] - 0s 536us/step - loss: 27.2765
Epoch 99/100
240/240 [==============================] - 0s 536us/step - loss: 26.9347
Epoch 100/100
240/240 [==============================] - 0s 540us/step - loss: 26.9030


In [11]:
# predicting the result of the test set

y_pred = ann.predict(X_test)

np.set_printoptions(precision=2)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[429.64 431.23]
 [460.64 460.01]
 [464.12 461.14]
 ...
 [471.35 473.26]
 [438.25 438.  ]
 [457.41 463.28]]
